services:
  - type: worker
    name: telegram-converter-bot
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    envVars:
      - key: BOT_TOKEN
        value: "8631494521:AAF-pG0Hwsx274QtGuoXCgs9R9xAlFxGoIo"
